In [4]:
from pymongo import MongoClient
import json
import numpy as np
import pandas as pd

# 1: Data Collection

In [5]:
file_path = 'C:/Users/viren/OneDrive/Desktop/IIT-MADARAS(GUVI)/data/airbnb_json/sample_airbnb.json'

# Read the json file

with open(file_path,'r') as file:
    airbnb_data = json.load(file)

# Convert JSON to DataFrame

In [6]:
df = pd.json_normalize(airbnb_data)

In [7]:
# Checking for null values.
df

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,review_scores.review_scores_accuracy,review_scores.review_scores_cleanliness,review_scores.review_scores_checkin,review_scores.review_scores_communication,review_scores.review_scores_location,review_scores.review_scores_value,review_scores.review_scores_rating,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,10.0,9.0,10.0,10.0,10.0,10.0,94.0,NaN,NaN,NaN
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,9.0,9.0,10.0,10.0,10.0,9.0,92.0,NaN,NaN,NaN
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,10.0,10.0,10.0,10.0,10.0,8.0,100.0,5000.0,NaN,NaN
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,10.0,8.0,10.0,10.0,10.0,10.0,92.0,1350.0,5000.0,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,10.0,9.0,10.0,10.0,10.0,9.0,95.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,Guests will have access to the 3 pools in the ...,...,10.0,9.0,10.0,10.0,10.0,9.0,92.0,NaN,NaN,NaN
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Newly renovated studio flat with full furniture.,,Newly renovated studio flat with full furniture.,,,,,...,10.0,9.0,10.0,10.0,10.0,9.0,85.0,NaN,NaN,NaN
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,,A bright large double room is available in a b...,,,The flat is exactly half way between the shops...,"Guests will have access to the full residence,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,,Apartamento amplo que acomoda 6 pessoas. Um qu...,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Handleing Missing Values

In [8]:
df.isnull().sum()

_id                                      0
listing_url                              0
name                                     0
summary                                  0
space                                    0
                                      ...
review_scores.review_scores_value     1475
review_scores.review_scores_rating    1474
weekly_price                          4841
monthly_price                         4899
reviews_per_month                     5461
Length: 77, dtype: int64

In [9]:
df.dtypes

_id                                    object
listing_url                            object
name                                   object
summary                                object
space                                  object
                                       ...
review_scores.review_scores_value     float64
review_scores.review_scores_rating    float64
weekly_price                          float64
monthly_price                         float64
reviews_per_month                     float64
Length: 77, dtype: object

In [10]:
# Select only numeric columns
numeric_df = df.select_dtypes(include=[np.number]) 

# Calculate correlation matrix
correlation_matrix = numeric_df.corr().abs()

# Identify pairs of columns with high correlation (e.g., > 0.9)
high_correlation_columns = set()
threshold = 0.9  # Adjust this threshold if needed
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if correlation_matrix.iloc[i, j] > threshold:
            colname = correlation_matrix.columns[i]
            high_correlation_columns.add(colname)

print("Highly correlated columns:\n", high_correlation_columns)

Highly correlated columns:
 {'reviews_per_month', 'host.host_total_listings_count', 'availability.availability_60', 'availability.availability_90', 'monthly_price'}

In [11]:
# Count of missing values in each column
missing_counts = df.isnull().sum()
print("Missing values per column:\n", missing_counts)

# Percentage of missing values in each column
missing_percentage = (df.isnull().mean() * 100)

Missing values per column:
 _id                                      0
listing_url                              0
name                                     0
summary                                  0
space                                    0
                                      ...
review_scores.review_scores_value     1475
review_scores.review_scores_rating    1474
weekly_price                          4841
monthly_price                         4899
reviews_per_month                     5461
Length: 77, dtype: int64

In [12]:
df['availability.availability_90'].unique()

array([ 0, 90, 40, 87, 29, 33, 67, 21, 35, 88, 74, 76, 31, 37, 43, 80, 84,
       25, 71, 19, 70, 16, 62,  5, 75, 26, 53, 24, 77, 55, 61, 11, 65, 82,
       83, 41, 48, 51, 46, 15, 60, 12, 64, 49,  3,  8, 27, 22, 63, 38, 68,
        1, 47, 85, 30, 42, 50, 52, 56, 89, 78, 13, 23, 44, 57, 39,  4, 10,
       28, 32, 36, 20, 45, 59, 86, 17, 79, 69, 73,  9, 81, 54, 14, 34, 58,
       18, 72,  7, 66,  6,  2], dtype=int64)

In [13]:
df['availability.availability_60'].unique()

array([ 0, 60, 24, 29, 19, 40, 10, 16, 58, 47, 57, 46, 31, 41, 13, 50, 54,
        3, 43, 45, 17, 26, 12, 36, 42,  5, 35, 52, 53, 11, 37, 25, 27, 32,
       39,  6, 18, 44, 14, 59, 38,  1, 22,  9, 21, 48,  7, 15, 20, 30,  4,
       23, 56, 49,  8, 33, 51, 34, 55,  2, 28], dtype=int64)

# Handle Missing Values in Numerical Columns

 Fill in missing values for numeric columns:

In [14]:
# For columns with significant numbers of missing values, such as' weekly_price' and' monthly_price', 
# consider filling with median values or creating a separate category for missing data to avoid bias.

df['weekly_price'].fillna(df['weekly_price'].median(), inplace=True)
df['monthly_price'].fillna(df['monthly_price'].median(), inplace=True)
df['reviews_per_month'].fillna(0,inplace=True)  # Assumes missing reviews means no reviews

C:\Users\viren\AppData\Local\Temp\ipykernel_6784\714029545.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weekly_price'].fillna(df['weekly_price'].median(), inplace=True)
C:\Users\viren\AppData\Local\Temp\ipykernel_6784\714029545.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['monthly_price'].fillna(df['monthly_price'].median(), inplace=True)
C:\Users\viren\AppData\Local\Temp\ipykernel_6784\714029545.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews_per_month'].fillna(0,inplace=True)  # Assumes missing reviews means no reviews

In [15]:
# Columns like review_scores.* may contain missing values because not every listing has reviews.
# Filling with median values for review scores can be reasonable, 
# but setting missing review scores to a separate category, 
# such as 0, is also viable if it represents an absence of reviews.


# Filling missing review scores with a neutral value or 0 for absence:

df['review_scores.review_scores_value'].fillna(0, inplace=True)
df['review_scores.review_scores_rating'].fillna(0, inplace=True)

C:\Users\viren\AppData\Local\Temp\ipykernel_6784\1343377294.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores.review_scores_value'].fillna(0, inplace=True)
C:\Users\viren\AppData\Local\Temp\ipykernel_6784\1343377294.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores.review_scores_rating'].fillna(0, inplace=True)

Handeling missing values in text columns

In [16]:
# Filling text columns with an empty string:

df['listing_url'].fillna('', inplace = True)
df['summary'].fillna('', inplace = True)
df['space'].fillna('', inplace = True)

C:\Users\viren\AppData\Local\Temp\ipykernel_6784\3863650786.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['listing_url'].fillna('', inplace = True)
C:\Users\viren\AppData\Local\Temp\ipykernel_6784\3863650786.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['summary'].fillna('', inplace = True)
C:\Users\viren\AppData\Local\Temp\ipykernel_6784\3863650786.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['space'].fillna('', inplace = True)

In [17]:
df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,review_scores.review_scores_accuracy,review_scores.review_scores_cleanliness,review_scores.review_scores_checkin,review_scores.review_scores_communication,review_scores.review_scores_location,review_scores.review_scores_value,review_scores.review_scores_rating,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,10.0,9.0,10.0,10.0,10.0,10.0,94.0,800.0,2800.0,0.0
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,9.0,9.0,10.0,10.0,10.0,9.0,92.0,800.0,2800.0,0.0
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,10.0,10.0,10.0,10.0,10.0,8.0,100.0,5000.0,2800.0,0.0
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,10.0,8.0,10.0,10.0,10.0,10.0,92.0,1350.0,5000.0,0.0
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,10.0,9.0,10.0,10.0,10.0,9.0,95.0,800.0,2800.0,0.0

# # Save DataFrame to CSV

In [18]:
df.to_csv('preprocessed_Airbnb_data.csv', index=False)

 # Connect to MongoDB

In [28]:
!pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.0.1

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from pymongo import MongoClient
import pandas as pd
from dotenv import load_dotenv
import os

# Loading the preprocessed data
df1 = pd.read_csv('preprocessed_Airbnb_data.csv')

# Connecting to MongoDB
load_dotenv()
password = os.getenv("roomno13")

client = MongoClient('mongodb+srv://virenemmanuel:{password}@airbnbdataset.wmlyq.mongodb.net/Airbnbanalysis?retryWrites=true&w=majority&appName=Airbnbdataset')

db = client['Airbnb_dataset']

collection = db['listingsAndReviews']

if isinstance(airbnb_data, dict):
    airbnb_data = [airbnb_data]


collection.insert_many(airbnb_data)